import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body> 
      <Navbar heading="Todo List"/> 
      <div className={inter.className}>{children}</div>
      </body>
    </html>
  );
}
// import { useEffect, useState } from "react";
// import { useRouter } from "next/router";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Navbar from "./components/Navbar";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   const router = useRouter();
//   const [heading, setHeading] = useState("Todo List");

//   useEffect(() => {
//     // Listen to route changes and update heading accordingly
//     switch (router.pathname) {
//       case "/about":
//         setHeading("About");
//         break;
//       case "/contact":
//         setHeading("Contact");
//         break;
//       default:
//         setHeading("Todo List");
//         break;
//     }
//   }, [router.pathname]);

//   return (
//     <html lang="en">
//       <body> 
//         <Navbar heading={heading}/> 
//         <div className={inter.className}>{children}</div>
//       </body>
//     </html>
//   );
// }

